#!/bin/sh -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
	if [ -d /usr/doc -a ! -e /usr/doc/Skeleton -a -d /usr/share/doc/Skeleton ]; then
		ln -sf ../share/doc/Skeleton /usr/doc/Skeleton
	fi
fi
# End automatically added section
# Automatically added by dh_installmenu
if test -x /usr/bin/update-menus ; then update-menus ; fi
# End automatically added section
